import Loading from "./Loading";
import Logo from "./Logo";
import Button from "./Button";
import Divider from "./Divider";
import Inputbox from "./Inputbox";
import Banner from "./Banner";
import Footer from "./Footer";
import Navbar from "./Navbar";
import Pagination from "./Pagination";
import Card from "./Card";
export { Loading, Logo ,Button,Divider,Inputbox ,Banner,Footer,Navbar,Pagination,Card};